apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-servlet1
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo-servlet
        image: registry.digitalocean.com/home-images/demo-servlet:latest
        ports:
        - containerPort: 8080